### ISSUE TITLE
clearing things up in burst

### ISSUE THREAD

**Issue by lanougue** [umr-lops/xsar#108]
Hello guys
I am jumping in xsar ! and already have some request / comment.
Here it is:
when I request "s1ds.s1meta.bursts()" I get a panda dataframe (that I just always transform in xarray) with missing information that I can find in "s1ds.s1meta._burst" which is indeed an xarray.Dataset !
Why don't just create a simple xarray Dataset with informations of both the two entities pre-cited that I can call easily call as "s1ds.s1meta.burst"? They all have common dimensions ! (and name could stay singular -burst- as in original xml file)

By the way, looking in attributes of "s1ds.s1meta._bursts", why linesPerBurst and "samplesPerBurst" have been renamed in "atrack_per_burst" and "xtrack_per_burst" ? Initial name is more logic/understandable for me and they may be stored as variable and not as attributes

**Comment by lanougue** [comment]
In fact, the final xarray.Dataset would look like the same as if I currently compute `burst = xr.merge([s1ds.s1meta.bursts().to_xarray(),s1ds.s1meta._bursts], combine_attrs='no_conflicts')`

**Comment by agrouaze** [comment]
closed with #118 .
