### ISSUE TITLE
moving history attribute to the good variable

### ISSUE THREAD

**Issue by lanougue** [umr-lops/xsar#109]
When I look at Dataset `s1ds.s1meta._bursts`, the attrs `history` of the dataset contains all the original pathes of the variables.
I beleive that, for example,  "- //product/swathTiming/burstList/burst/lastValidSample" is the history of variable " lastValidSample".
I thus think that each variable of the dataset should have their own "history" attrs that contain the original path

**Comment by oarcher** [comment]
Probably related to #50

**Comment by agrouaze** [comment]
closed with  #118
