### ISSUE TITLE
Can't open WV dataset

### ISSUE THREAD

**Issue by rmarquarlops** [umr-lops/xsar#114]
**xsar version**
'0.8.4.dev10+gdaa434a'

**Description of expected behavior and the observed behavior**
When trying to open a WV file from 2019, I get `AttributeError: type object 'Sentinel1Meta' has no attribute platform'`

**Code for reproduction**
```
path = "SENTINEL1_DS:/home/datawork-cersat-public/cache/project/mpc-sentinel1/data/esa/sentinel-1a/L1/WV/S1A_WV_SLC__1S/2019/175/S1A_WV_SLC__1SSV_20190624T120411_20190624T122726_027821_03240A_68A5.SAFE:WV_015"
sar_meta = xsar.product_info(path)['meta'].iloc[0]
xsar.open_dataset(path)
```

**Comment by agrouaze** [comment]
Issue reproduced with additional line:
`cli  = dask.distributed.Client()`
explanation: the s1meta is definied as `BlockingActorProxy` when using dask cluster and it needs all the attributes to be defined in the  `__init__`.
adding `platform = None` should indeed solve the issue.
