### ISSUE TITLE
Change installation guide (readme and installing.rst)

### ISSUE THREAD

**Issue by yreynaud** [umr-lops/xsar#152]
RCM is being merged with xsar in PR (https://github.com/umr-lops/xsar/pull/151). Readers installation is now optional (not to install all the readers if not needed).
A new syntax appear for pip installation depending if we want to use Radarsat2, RCM or both : `pip install xsar[RCM,RS2]`. This syntax search for readers on pypi.
The problem is that for the moment `xarray-safe-rcm` isn't on pypi. So, when it will be uploaded, we will have to modify the installation guide in `readme.md` and `docs/installing.rst` with this new syntax.

**Comment by agrouaze** [comment]
closed with #151
