### ISSUE TITLE
land_mask error

### ISSUE THREAD

**Issue by vincelhx** [umr-lops/xsar#197]
```python 
path = "/home/datawork-cersat-public/cache/project/mpc-sentinel1/data/esa/sentinel-1b/L1/EW/S1B_EW_GRDH_1S/2016/309/S1B_EW_GRDH_1SDV_20161104T095510_20161104T095622_002807_004C13_1B2D.SAFE"   
L1_ds = xsar.Sentinel1Dataset(path,resolution='1000m')
```
![image](https://github.com/umr-lops/xsar/assets/38355798/b2294479-ef3a-4d56-a0a7-6014a543d03b)

déjà vu @agrouaze ? c'est suppposé être en pleine mer

**Comment by agrouaze** [comment]
Looking at the geographic location it seems that this image was acquired in the middle of Amazon rain forest. 
![image](https://github.com/umr-lops/xsar/assets/14925067/33d664e5-8cd7-400f-8180-8930fc10b489)

**Comment by vincelhx** [comment]
@agrouaze oups... looked at wrong location
but why do we have this on disk?

**Comment by agrouaze** [comment]
For calibration over rain forest!
