### ISSUE TITLE
Unable to work with RCM Dataset.

### ISSUE THREAD

**Issue by sparshgarg23** [umr-lops/xsar#199]
So I am currently working on RCM datasets and I thought of using your repository.
Unfortunately the example RCM.ipynb isn't working because when you execute the cell
```
path = xsar.get_test_file('RCM1_OK1050603_PK1050605_1_SC50MB_20200214_115905_HH_HV_Z010')
```
The file doesn't download.Whereas when I work with the radarsat 2 example,the file is able to download and I am able to access the metadata.

Secondly,since I thought this was an issue in downloading the file.I provided my own file.The  code and structure of the folder is shown below
Code
```
import xsar
meta=xsar.RcmMeta('Name of RCM folder')
in this case it's RCM1_OK2137170_PK2304568_1_FSL24_20221018_123926_HH_SLC
```
![structure_rcm](https://github.com/umr-lops/xsar/assets/34626942/49270c2d-dda0-4266-8bb2-92856bcb8c9e)

However doing this results in the following error
type error iteration over a 0-d array
Any reason why this error is happening?

**Comment by agrouaze** [comment]
Hello @sparshgarg23 ,
I think, `xsar` is not working because `xarray-safe-rcm`  is handling only GRD and you try to open a SLC product.
Do you confirm?
For now, it is not in our roadmap to update `xarray-safe-rcm`  for SLC products but feel free to propose a pull request, we would be very happy to review it.
Cheers

**Comment by sparshgarg23** [comment]
@agrouaze  that's sad to hear.Are there any other python based libraries which can be used to read RCM files in SLC format.

**Comment by agrouaze** [comment]
> @agrouaze that's sad to hear.Are there any other python based libraries which can be used to read RCM files in SLC format.

If there is such a python lib, I don't know it.
