### ISSUE TITLE
`xsar` not compatible with `numpy==2.0.0`

### ISSUE THREAD

**Issue by agrouaze** [umr-lops/xsar#214]

**Comment by agrouaze** [comment]
For now `geoviews` dependency needed in the sphinx documentation required `numpy<2.0.0` , let's wait for the bumps.

**Comment by Skealz** [comment]
If this is meant to take time, It would be great to pin numpy in the dependencies, because I have repin it myself each time I install xsar

**Comment by agrouaze** [comment]
I just tested and there is no more conflict with `geoviews`.
I opened a PR to solve the compatilibity : https://github.com/umr-lops/xsar/pull/216
