### ISSUE TITLE
noise lut range not defined over all image for WV with ipf>=2.9

### ISSUE THREAD

**Issue by oarcher** [umr-lops/xsar#3]
Noise lut range is not defined over all image for WV with ipf>=2.9
![image](https://user-images.githubusercontent.com/4264660/117577864-e32b4900-b0eb-11eb-8dc2-eddcf61f310e.png)

But it's ok for ipf<2.9
![image](https://user-images.githubusercontent.com/4264660/117577814-a8291580-b0eb-11eb-9354-2a9601697237.png)

**Comment by oarcher** [comment]
For ipf<2.9, in noise annotation file, `<noiseVector>` is defined up to azimuth 6601, so all image is covered. (However, it's strange, because 6601 is **outside** the image)

For ipf>=2.9, the last `<noiseRangeVector>` is defined at azimuth 3300, that is inside the image.

From ESA [thermal denoising](https://sentinel.esa.int/web/sentinel/user-guides/sentinel-1-sar/document-library/-/asset_publisher/1dO7RF5fJMbd/content/thermal-denoising-of-products-generated-by-the-sentinel-1-ipf) document, the noise is taken from the closest block.

So we are allowed to extend the last block to include the whole image.

![image](https://user-images.githubusercontent.com/4264660/117578731-0952e800-b0f0-11eb-8fb1-ad4e7fcc6807.png)

It's quite strange to see that's it's not seems to be as accurate as ipf<2.9 ...

**Comment by agrouaze** [comment]
It seems that this issue is not totally solved : 
![image](https://user-images.githubusercontent.com/14925067/158824596-e2425a80-3d84-449a-941b-17695c9b382c.png)
this figure come from the sigma0 variable from `xsar`. it seems that all product WV SLC in IPF2.9 (in which the noise annotation changed) are underestimated.

**Comment by oarcher** [comment]
Reopenned, as we have similar cases
