### ISSUE TITLE
use xml to read GCPs, instead of tiff file

### ISSUE THREAD

**Issue by oarcher** [umr-lops/xsar#42]
GCPs in tiff files only provide (`'longitude'`, `'latitude'`, `'height'`). In the xml file, some variables are also provided, like `'azimuth_time'`, `'slant_range_time'`, `'incidence'`, and `'elevation'`.

PR #38 from @agrouaze has done most of the work to read those variables from xml file, but to reduce the PR size, we can do a specific PR on this item.

The new structure can be called `s1meta.geoloc`, but after some validation, it will replace `s1meta.gcps`, as `s1meta.gcps` is a subset of `s1meta.geoloc`.

`geoloc` might be added as a  `compound_var` in `sentinel1_xml_mappings`.

**Comment by agrouaze** [comment]
this issue is closed with #57
