### ISSUE TITLE
Rasterization (ie interpolation on image grid) from geolocation needs homogeneization among params

### ISSUE THREAD

**Issue by agrouaze** [umr-lops/xsar#56]
the geolocationGrid annotations contains several fields:
['longitude', 'latitude', 'height', 'azimuth_time', 'slant_range_time','incidence','elevation']
Currently they all use a method for decoding : `geolocation_grid` expcet `elevation` & `incidence` that use `annotation_angle` method.
These methods don't return the same type of object. It is something that is important at the rasterization step in `sentinel_dataset.py`.
This issue has already been addressed in PR #38 but it will be effectively merge from a future PR dedicated to this rasterization step.

- [ ] change `func` in `senitinel_xml_mappings.py` for elevation and incidence
- [ ] add elevation and incidence in the `s1meta.geoloc` xarray
- [ ] homogeneize the method in `sentinel1_dataset.py` to get the HR variables described in geolocationGrid annotations.

**Comment by oarcher** [comment]
from work done in #46, related to #42
