### ISSUE TITLE
use gdal>=3.3, rasterio>=1.2 for rms

### ISSUE THREAD

**Issue by oarcher** [umr-lops/xsar#8]
Once required deps will be available, we will switch from 'average' to 'rms' by default. 
(ie change all occurrences from `rasterio.enums.Resampling.average` to `asterio.enums.Resampling.rms`

But for now, we have to use 'average' to get most of CD/CI tests to pass (see #7)

**Comment by oarcher** [comment]
Here is the gdal 3.3 workflow test : https://github.com/umr-lops/xsar/actions/workflows/check-gdal3.3-available.yml
While it fail, we can't do anything here

**Comment by oarcher** [comment]
@alevieux , from https://github.com/umr-lops/xsar/issues/7#issuecomment-889893237 , about forcing rasterio>=1.2.6 :

Let's have the same installation procedure for every OS. It will fail for py3.6 on windows, but that not a big problem.
Can you submit a PR for that ?

**Comment by alevieux** [comment]
Conda install Rasterio 1.1.0 on python 3.7 and Rasterio 1.2.6 on python 3.6, 3.8 and 3.9 and I think it's better to have Rasterio 1.2.6 ?

For windows when you force the Rasterio 1.2.6 is not exist just for python 3.6, I think just inform user the rms is not available in python 3.6 for windows
For Mac the installation in python 3.7 and 3.8 must install tbb package and for windows  the installation in python 3.7 and 3.8 must install Fiona package. It's specific, we can add in doc a warning for installation ?
