### ISSUE TITLE
footprint / index issue WV product

### ISSUE THREAD

**Issue by agrouaze** [umr-lops/xsar#80]
issue spotted by https://github.com/owenod1
`Salut, when using xsar's .footprint function on sentinel-1 WV train metadata the returned imagette footprints appear to follow a different sorting than the file listing (e.g. footprints 3,4 and 5 belongs to imagettes 23, 21 and 22). When retrieving the imagette footprints from the subdataset directly the footprints are sorted correctly but this requires to open the subdatasets individually. Is there a xsar way to connect the correct footprints directly to files without having to open the individual subdatasets?

example of the issue:

```
train = '/home/datawork-cersat-public/cache/project/mpc-sentinel1/data/esa/sentinel-1a/L1/WV/S1A_WV_SLC__1S/2019/328/S1A_WV_SLC__1SSV_20191124T112814_20191124T113354_030052_036E86_6C90.SAFE'
right = [xsar.open_dataset(i).footprint.centroid.coords[0] for i in xsar.Sentinel1Meta(train).subdatasets]  # slow but correct
wrong = [i.centroid.coords[0] for i in xsar.Sentinel1Meta(train).footprint] # fast but unsorted
```
![image](https://user-images.githubusercontent.com/14925067/165297605-fd9bd406-5c16-42be-abf2-88241e107e62.png)

here a correct decreasing latitude is shown for descending train when loading the footprints individually, but when loading the footprints from the metadata directly the latitudes (and thus the footprints) follow an incorrect pattern
`

**Comment by oarcher** [comment]
Perhaps that there is a way to make it clearer for the user.

currently, `s1meta.subdatasets` and `s1meta.manifest_attrs['footprints']` are zippable list.

We might consider to make `s1meta.subdatasets` be a geodataframe, with index from `subdatasets`, and geometry from `manifest_attrs['footprints']`

**Comment by oarcher** [comment]
In #81, I've choose to recursively open all TOPS _IW_SLC_ subdatasets, to get their individual footprint.

This slow down a little the product opening, but I think it's an acceptable solution, as the subdataset count is low (3)

**Comment by owenodriscoll** [comment]
@oarcher the code works using your fork, cheers
